### ISSUE TITLE
"Welcome Text" inaccurate

### ISSUE THREAD

**Issue by radio-alice** [automerge/pushpin#372]
Welcome text says "Quick travel around by clicking the Omnibox (map icon)", but it seems that it's now a magnifying glass icon. I fixed this and edited some of the other welcome text to better match the UI [here](https://github.com/automerge/pushpin/compare/master...radio-alice:fix-intro-text). Should I PR?

P.S. This is such a cool project, thanks for making it happen!

**Comment by pvh** [comment]
(Closing since I believe this is resolved!)
