### ISSUE TITLE
ipc.config.socketRoot never set

### ISSUE THREAD

**Issue by raphael10-collab** [automerge/pushpin#397]
Here https://github.com/automerge/pushpin/blob/master/src/apps/clipper-host/index.ts#L29  "ipc.config.socketRoot" is used by its value is never set: https://github.com/automerge/pushpin/blob/master/src/ipc.ts

**Comment by jeffpeterson** [comment]
The default `socketRoot` is `"/tmp"` according to the [readme](https://www.npmjs.com/package/node-ipc#ipc-config).
